apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: troubleshot
    group: troubleshot
    project: sandbox-modolo
  name: troubleshot
  namespace: sandbox-modolo
spec:
  failedBuildsHistoryLimit: 2
  nodeSelector: null
  source:
    type: Dockerfile 
    dockerfile: |-
      FROM alpine:latest

      RUN apk add iproute2 rsync vim python3 go py3-pip bash sudo openssh bind-tools
      RUN mkdir -p /opt/troubleshot/bin
      RUN chgrp -R 0 /opt/troubleshot && \
          chmod -R g+rwX /opt/troubleshot
      ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/troubleshot/bin

      WORKDIR /opt/troubleshot

      CMD [ "/bin/bash" ]
  postCommit: {}
  resources: {}
  runPolicy: Serial      
  strategy:
    type: Docker
    dockerStrategy: {}
  output:
    to:
      kind: "DockerImage"
      name: "172.30.186.243:5000/sandbox-modolo/troubleshot"
  successfulBuildsHistoryLimit: 2
