apiVersion: v1
kind: DeploymentConfig
metadata:
  name: troubleshot
  labels:
    app: troubleshot
    project: sandbox-modolo
    type: application
spec:
  replicas: 1
  template:
    metadata:
      labels:
        project: sandbox-modolo
        type: application
    spec:
      containers:
      - name: troubleshot
        image: 172.30.186.243:5000/sandbox-modolo/troubleshot
        resources: {}
        imagePullPolicy: Always
