apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: troubleshot
    group: troubleshot
    project: sandbox-modolo
  name: troubleshot
  namespace: sandbox-modolo
spec:
  failedBuildsHistoryLimit: 2
  nodeSelector: null
  source:
    type: Git 
    git:
      uri: https://github.com/mrmodolo/openshift-troubleshot.git 
  postCommit: {}
  resources: {}
  runPolicy: Serial      
  strategy:
    type: Docker
    dockerStrategy:
  output:
    to:
      kind: "DockerImage"
      name: "image-registry.openshift-image-registry.svc:5000/sandbox-modolo/troubleshot"
  successfulBuildsHistoryLimit: 2
