apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-pods-to-sa
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: view-pods
  apiGroup: rbac.authorization.k8s.io
